# Generated by Django 3.2.7 on 2021-09-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('available', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
