# Generated by Django 3.2.7 on 2021-09-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
