# Generated by Django 3.2.7 on 2021-10-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20211010_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
